### ISSUE TITLE
相机参数的baseline和深度找不到

### ISSUE THREAD

**Issue by SlamMate** [fusionportable/fusionportable_dataset_tools#1]
我在将相机标定参数转为kitti的orbSLAM3的相机格式方面遇到了问题。文件内似乎没有给出必需的baseline参数和深度参数。我用python查看了session文件，文件里也没有相关的信息。如果您方便的话，可以提供您数据集两个摄像头双目设定下的更多参数信息吗？

**Comment by gogojjh** [comment]
We have provided the camera matrix, rectification matrix, projection matrix, and extrinsics (including the baseline) for cameras (http://filebrowser.ram-lab.com/share/I67uNo6q, pwd: fusionportable). But our provided images are raw, you need to manually rectify images (as done by KITTI).
