### ISSUE TITLE
How to find the corresponding calibration file for each rosbag data file?

### ISSUE THREAD

**Issue by wlxing1901** [fusionportable/fusionportable_dataset_tools#10]
Your dataset and work are excellent; such a comprehensive and diverse dataset has made a significant contribution to the entire SLAM community. I hope to use your dataset in my work and cite your paper. 

I encountered a problem during use, which is that the rosbag data itself is classified according to the collection platform, but the calibration files are categorized by date. For instance, if I want to use the 'ugv_parking03.bag' file, in which date should I look for the corresponding calibration parameters in the calibration_files? Additionally, are different data from the same platform, such as 'ugv_parking01.bag' and 'ugv_parking03.bag', collected on the same day, and would their extrinsic parameters change?

**Comment by gogojjh** [comment]
Here is the configure file to indicate the specific calibration file for a specfic rosbag: https://github.com/fusionportable/fusionportable_dataset_tools/blob/main/cfg/dataset/cfg_sequence.py

It is not complete. But the direct rule is that the same platform will use the same calibration file.
