### ISSUE TITLE
about the map evaluation tool

### ISSUE THREAD

**Issue by Yiiboo-w** [fusionportable/fusionportable_dataset_tools#15]
Thanks for providing such useful tools in the slam field.
A few images in the map evaluation tool cannot be loaded, could you upload them again? Thanks so much!
![image](https://github.com/fusionportable/fusionportable_dataset_tools/assets/91960557/93d85e20-a429-46c3-90e8-4eb70eb8335d)

**Comment by Yiiboo-w** [comment]
Additionally, these images can also not be loaded. Thx!!
![image](https://github.com/fusionportable/fusionportable_dataset_tools/assets/91960557/be10dc46-aec3-4414-995a-98ed5288ecfc)

**Comment by JokerJohn** [comment]
@ybwang99 sorry for this， we have already solved this problem, pls check it.
<img width="1286" alt="image" src="https://github.com/fusionportable/fusionportable_dataset_tools/assets/25702851/0ae5dc99-9254-4134-b370-11c7af0ac52a">

**Comment by ybwang99** [comment]
> @ybwang99 sorry for this， we have already solved this problem, pls check it. <img alt="image" width="1286" src="https://private-user-images.githubusercontent.com/25702851/339592602-0ae5dc99-9254-4134-b370-11c7af0ac52a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgzMjg4MTQsIm5iZiI6MTcxODMyODUxNCwicGF0aCI6Ii8yNTcwMjg1MS8zMzk1OTI2MDItMGFlNWRjOTktOTI1NC00MTM0LWIzNzAtMTFjN2FmMGFjNTJhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjE0VDAxMjgzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNjYjE2ZWJkMDJiNzk0ZDYzMDM5NWU3MjA5MjhkZmVmZDI5YzM2OTA1OTAzNzk0NzQ3YjJjNTJlNjEyZjM3NWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ag8sIpmWd9V06wQDeY_WRpcp6oCfVLrmtbZyOEfMoIY">



> @ybwang99 sorry for this， we have already solved this problem, pls check it. <img alt="image" width="1286" src="https://private-user-images.githubusercontent.com/25702851/339592602-0ae5dc99-9254-4134-b370-11c7af0ac52a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgzMjg4MTQsIm5iZiI6MTcxODMyODUxNCwicGF0aCI6Ii8yNTcwMjg1MS8zMzk1OTI2MDItMGFlNWRjOTktOTI1NC00MTM0LWIzNzAtMTFjN2FmMGFjNTJhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjE0VDAxMjgzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNjYjE2ZWJkMDJiNzk0ZDYzMDM5NWU3MjA5MjhkZmVmZDI5YzM2OTA1OTAzNzk0NzQ3YjJjNTJlNjEyZjM3NWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ag8sIpmWd9V06wQDeY_WRpcp6oCfVLrmtbZyOEfMoIY">

Thanks for your quick response! It's clear now.

**Comment by Yiiboo-w** [comment]
Thanks for your quick response! It's clear now.
