### ISSUE TITLE
Ouster雷达metadata文件

### ISSUE THREAD

**Issue by RoboFeng** [fusionportable/fusionportable_dataset_tools#2]
请问能提供一下数据集中使用的ouster雷达的metadata文件吗？

**Comment by gogojjh** [comment]
{
    "base_pn": "",
    "base_sn": "",
    "beam_altitude_angles": 
    [
        21.31,
        21,
        20.69,
        20.34,
        20.06,
        19.75,
        19.42,
        19.09,
        18.81,
        18.48,
        18.14,
        17.82,
        17.52,
        17.19,
        16.86,
        16.51,
        16.22,
        15.87,
        15.55,
        15.21,
        14.89,
        14.57,
        14.22,
        13.88,
        13.57,
        13.22,
        12.87,
        12.53,
        12.21,
        11.86,
        11.53,
        11.17,
        10.85,
        10.51,
        10.16,
        9.81,
        9.47,
        9.14,
        8.79,
        8.43,
        8.08,
        7.75,
        7.39,
        7.06,
        6.7,
        6.36,
        5.99,
        5.66,
        5.3,
        4.95,
        4.6,
        4.26,
        3.89,
        3.55,
        3.2,
        2.85,
        2.5,
        2.15,
        1.78,
        1.45,
        1.09,
        0.72,
        0.37,
        0.02,
        -0.34,
        -0.69,
        -1.04,
        -1.38,
        -1.75,
        -2.11,
        -2.43,
        -2.8,
        -3.17,
        -3.52,
        -3.84,
        -4.21,
        -4.57,
        -4.91,
        -5.26,
        -5.6,
        -5.99,
        -6.32,
        -6.64,
        -7.01,
        -7.38,
        -7.7,
        -8.04,
        -8.39,
        -8.77,
        -9.08,
        -9.42,
        -9.78,
        -10.13,
        -10.46,
        -10.81,
        -11.14,
        -11.51,
        -11.83,
        -12.16,
        -12.48,
        -12.85,
        -13.18,
        -13.51,
        -13.83,
        -14.19,
        -14.52,
        -14.84,
        -15.14,
        -15.52,
        -15.83,
        -16.15,
        -16.47,
        -16.82,
        -17.14,
        -17.47,
        -17.76,
        -18.12,
        -18.43,
        -18.73,
        -19.04,
        -19.39,
        -19.69,
        -19.99,
        -20.29,
        -20.63,
        -20.93,
        -21.21,
        -21.51
    ],
    "beam_azimuth_angles": 
    [
        4.32,
        1.45,
        -1.36,
        -4.18,
        4.3,
        1.45,
        -1.38,
        -4.18,
        4.28,
        1.45,
        -1.36,
        -4.18,
        4.26,
        1.45,
        -1.37,
        -4.19,
        4.28,
        1.45,
        -1.37,
        -4.19,
        4.27,
        1.45,
        -1.38,
        -4.19,
        4.26,
        1.44,
        -1.38,
        -4.19,
        4.26,
        1.44,
        -1.38,
        -4.2,
        4.25,
        1.45,
        -1.39,
        -4.2,
        4.24,
        1.45,
        -1.39,
        -4.2,
        4.24,
        1.43,
        -1.39,
        -4.19,
        4.24,
        1.43,
        -1.4,
        -4.18,
        4.23,
        1.42,
        -1.4,
        -4.2,
        4.24,
        1.42,
        -1.4,
        -4.2,
        4.24,
        1.43,
        -1.41,
        -4.2,
        4.24,
        1.4,
        -1.4,
        -4.21,
        4.23,
        1.41,
        -1.4,
        -4.21,
        4.23,
        1.4,
        -1.4,
        -4.22,
        4.22,
        1.4,
        -1.4,
        -4.22,
        4.22,
        1.41,
        -1.41,
        -4.21,
        4.21,
        1.4,
        -1.4,
        -4.22,
        4.21,
        1.41,
        -1.41,
        -4.22,
        4.21,
        1.41,
        -1.41,
        -4.23,
        4.22,
        1.4,
        -1.42,
        -4.22,
        4.21,
        1.4,
        -1.42,
        -4.22,
        4.22,
        1.4,
        -1.43,
        -4.22,
        4.2,
        1.39,
        -1.43,
        -4.22,
        4.21,
        1.4,
        -1.43,
        -4.23,
        4.21,
        1.38,
        -1.44,
        -4.23,
        4.2,
        1.38,
        -1.42,
        -4.24,
        4.2,
        1.38,
        -1.43,
        -4.24,
        4.2,
        1.38,
        -1.43,
        -4.24
    ],
    "build_date": "2022-06-08T01:26:30Z",
    "build_rev": "v2.3.1",
    "client_version": "0.2.1",
    "data_format": 
    {
        "column_window": 
        [
            0,
            1023
        ],
        "columns_per_frame": 1024,
        "columns_per_packet": 16,
        "pixel_shift_by_row": 
        [
            24,
            16,
            8,
            0,
            24,
            16,
            8,
            0,
            24,
            16,
            8,
            0,
            24,
            16,
            8,
            0,
            24,
            16,
            8,
            0,
            24,
            16,
            8,
            0,
            24,
            16,
            8,
            0,
            24,
            16,
            8,
            0,
            24,
            16,
            8,
            0,
            24,
            16,
            8,
            0,
            24,
            16,
            8,
            0,
            24,
            16,
            8,
            0,
            24,
            16,
            8,
            0,
            24,
            16,
            8,
            0,
            24,
            16,
            8,
            0,
            24,
            16,
            8,
            0,
            24,
            16,
            8,
            0,
            24,
            16,
            8,
            0,
            24,
            16,
            8,
            0,
            24,
            16,
            8,
            0,
            24,
            16,
            8,
            0,
            24,
            16,
            8,
            0,
            24,
            16,
            8,
            0,
            24,
            16,
            8,
            0,
            24,
            16,
            8,
            0,
            24,
            16,
            8,
            0,
            24,
            16,
            8,
            0,
            24,
            16,
            8,
            0,
            24,
            16,
            8,
            0,
            24,
            16,
            8,
            0,
            24,
            16,
            8,
            0,
            24,
            16,
            8,
            0
        ],
        "pixels_per_column": 128,
        "udp_profile_imu": "LEGACY",
        "udp_profile_lidar": "LEGACY"
    },
    "hostname": "os-122143000943.local",
    "image_rev": "ousteros-image-prod-aries-v2.3.1+20220608012528.patch-v2.3.x",
    "imu_to_sensor_transform": 
    [
        1,
        0,
        0,
        6.253,
        0,
        1,
        0,
        -11.775,
        0,
        0,
        1,
        7.645,
        0,
        0,
        0,
        1
    ],
    "initialization_id": 9599937,
    "json_calibration_version": 3,
    "lidar_mode": "1024x10",
    "lidar_origin_to_beam_origin_mm": 15.806,
    "lidar_to_sensor_transform": 
    [
        -1,
        0,
        0,
        0,
        0,
        -1,
        0,
        0,
        0,
        0,
        1,
        36.18,
        0,
        0,
        0,
        1
    ],
    "prod_line": "OS-1-128",
    "prod_pn": "840-102145-05",
    "prod_sn": "122143000943",
    "proto_rev": "",
    "status": "RUNNING"
}
