### ISSUE TITLE
Download not working

### ISSUE THREAD

**Issue by patripfr** [fusionportable/fusionportable_dataset_tools#3]
Hi,
thanks for creating this extensive dataset! 
Unfortunately, I can't download the data. If I click on the [links to download ](https://ram-lab.com/file/site/fusionportable/dataset/fusionportable/#download) the data, the website doesn't load.
Are the links still correct?

**Comment by gogojjh** [comment]
Hi Patrick, the server was restarted. Please try this link again. Thanks!

**Comment by patripfr** [comment]
thanks, it works now :)
