### ISSUE TITLE
Password for dataset download

### ISSUE THREAD

**Issue by 78748547** [fusionportable/fusionportable_dataset_tools#4]
Hello! I am preparing to download the “sensor_data” on the FusionPortable interface. But when I clicked on the link, I went to http://filebrowser.ram-lab.com/share/qEhtb7Cl . It seems that this interface requires a password to unlock? May I ask what I should do about this?

**Comment by gogojjh** [comment]
pwd is fusionportable

**Comment by 78748547** [comment]
> pwd is fusionportable

Thank you! I accidentally overlooked it.
