### ISSUE TITLE
How to download data

### ISSUE THREAD

**Issue by wsp666** [fusionportable/fusionportable_dataset_tools#5]
Dear RAM LAB,
I hope this message finds you well. I am interested in obtaining access to the FusionPortable dataset and would like to kindly request information on the download process. Additionally, I am curious if there are any plans to open-source the dataset, and if so, I would appreciate details on the timeline and any specific procedures involved.
Best regards,

**Comment by gogojjh** [comment]
Hi, please visit https://fusionportable.github.io/dataset/fusionportable and click link in the **Download** section:
<img width="875" alt="image" src="https://github.com/HKUSTGZ-IADC/iadc_dataset_tools/assets/11897988/0483225a-fbda-4af2-86b7-dd6e653d21d2">

For the open-source FusionPortablev2, it should be released in January, 2024. We have collected all data. We are now checking each rosbag and conducting some benchmark experiments.

**Comment by wsp666** [comment]
> Hi, please visit https://fusionportable.github.io/dataset/fusionportable and click link in the **Download** section: <img alt="image" width="875" src="https://private-user-images.githubusercontent.com/11897988/286788663-0483225a-fbda-4af2-86b7-dd6e653d21d2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDEzMjA1NDgsIm5iZiI6MTcwMTMyMDI0OCwicGF0aCI6Ii8xMTg5Nzk4OC8yODY3ODg2NjMtMDQ4MzIyNWEtZmJkYS00YWYyLTg2YjctZGQ2ZTY1M2QyMWQyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTMwVDA0NTcyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ0MDMzNGNhMmU0MDM4OTU1NWU5YWFlMzMwMTNhNWFjZTJhODIzYjg4YmUzYzFjYTUwMGI3MGZlNjExYzE3MzMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.d9l01YJG9Ux7VZEIZHPCVosfr-5FH5L1VJVask_-mhU">
> 
> For the open-source FusionPortablev2, it should be released in January, 2024. We have collected all data. We are now checking each rosbag and conducting some benchmark experiments.

Thank you for your prompt. However, After I opened the above link, the webpage jumped to [http://filebrowser.ram-lab.com/share/qEhtb7Cl](http://filebrowser.ram-lab.com/share/qEhtb7Cl), the login password is required as following shown.
![image](https://github.com/HKUSTGZ-IADC/iadc_dataset_tools/assets/56908997/b1285e3e-43d1-4f0b-92c2-c5b772427ea4)
