### ISSUE TITLE
无法下载单个 .bag.7z文件

### ISSUE THREAD

**Issue by zzwu29** [fusionportable/fusionportable_dataset_tools#6]
您好，感谢您贡献的开源数据集！
当我尝试下载某个压缩的bag时，我遇到了如下的问题
<img width="1069" alt="image" src="https://github.com/HKUSTGZ-IADC/iadc_dataset_tools/assets/44901540/7d1fa429-1d43-4fcd-b26f-cf8fa59a78ca">

<img width="304" alt="image" src="https://github.com/HKUSTGZ-IADC/iadc_dataset_tools/assets/44901540/178d5160-8126-4ad5-8a4f-3add72a94647">

<img width="834" alt="image" src="https://github.com/HKUSTGZ-IADC/iadc_dataset_tools/assets/44901540/e88e9527-6d97-410d-8bf8-ef949c6e22c4">

因此，我只能通过左侧的“下载”按钮，但我发现这事实上是整个大文件夹的下载，不是我想要的解决方案。
请问应该如何下载单个数据集的.bag.7z文件呢？

**Comment by gogojjh** [comment]
你好 双击之后应该能看到这个界面
![image](https://github.com/HKUSTGZ-IADC/iadc_dataset_tools/assets/11897988/4cdf6282-c090-4654-a121-59d2130e0732)
你可以试下扫描这个二维码, 看看能否下载?
服务器在香港, 有可能需要点魔法进行上网

**Comment by zzwu29** [comment]
> 你好 双击之后应该能看到这个界面 ![image](https://private-user-images.githubusercontent.com/11897988/291259302-4cdf6282-c090-4654-a121-59d2130e0732.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI4OTc4MDUsIm5iZiI6MTcwMjg5NzUwNSwicGF0aCI6Ii8xMTg5Nzk4OC8yOTEyNTkzMDItNGNkZjYyODItYzA5MC00NjU0LWExMjEtNTlkMjEzMGUwNzMyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE4VDExMDUwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE0MzU4YzAyMzQxNjc0ZWNjNzZkNTRmYTYyOTY4Nzg0ZjlmZjlkYWY3NDBjNmJmZDdiNDZiZWY3YzE2MjVkNzkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.3OATtoGktcCe9OJkfd3gldfDTTxVPW8g2bZdpF7Tjjc) 你可以试下扫描这个二维码, 看看能否下载? 服务器在香港, 有可能需要点魔法进行上网

谢谢～请问该数据集的雷达、相机和IMU均是硬件同步的吗？

**Comment by gogojjh** [comment]
是的 硬件是通过FPGA进行信号trigger, 但软件上并没有进行同步, 即每个传感器的时间戳由软件驱动收到传感器信号的时刻给予ROS时间戳. 但经我们测试, 不同传感器之间的时间戳相差较少 (<5ms)
