### ISSUE TITLE
bug: the calibration link returns 404

### ISSUE THREAD

**Issue by lucky9-cyou** [fusionportable/fusionportable_dataset_tools#8]
![image](https://github.com/HKUSTGZ-IADC/iadc_dataset_tools/assets/56758695/08562886-aa17-4116-a2b0-812d65e3c6c4)

maybe you should make that repo public

**Comment by lucky9-cyou** [comment]
When using calibration files from http://filebrowser.ram-lab.com/share/I67uNo6q/20220626_calib/calib/. I got following errors when load yaml:
![image](https://github.com/HKUSTGZ-IADC/iadc_dataset_tools/assets/56758695/9f3951f3-8fdb-403e-85f9-d7ba0a8f248e)

**Comment by lucky9-cyou** [comment]
Another issue concerns projecting the point cloud onto the camera plane. Why use the relative transform matrix between the camera and body IMU as the rotation matrix?

In write_data_to_kitti360.ipynb:
![image](https://github.com/HKUSTGZ-IADC/iadc_dataset_tools/assets/56758695/0d7d2633-8a6f-41bd-b180-ccf3a5e3d708)

But when i using same transform matrix with following code, I got the wrong results:
![image](https://github.com/HKUSTGZ-IADC/iadc_dataset_tools/assets/56758695/8c0c2c5c-55aa-4968-bcc8-e357eec786af)

The point cloud projections onto the camera were correct for the first few frames, but most of the subsequent frames were basically incorrect:
![image](https://github.com/HKUSTGZ-IADC/iadc_dataset_tools/assets/56758695/a5a34eb2-e188-4008-93cc-d4268b222edf)
The above is 501.png in 20220219_MCR_normal_00

**Comment by lucky9-cyou** [comment]
I believe the issue lies with the calibration file. In write_data_to_kitti360.ipynb, you reference 20230618_calib, but on https://fusionportable.github.io/dataset/fusionportable/, only data from 2022 is available.

**Comment by gogojjh** [comment]
The calibration_files has been made public.
It seems that the format is made with minor modifications compared with the original calibration files: I deleted the original ```!! opencv-matrix'''
Could you please try the new one first?

**Comment by lucky9-cyou** [comment]
> The calibration_files has been made public. It seems that the format is made with minor modifications compared with the original calibration files: I deleted the original ```!! opencv-matrix''' Could you please try the new one first?

For 2023 calibration files, it is ok. But it is not ok for 2022 calibration files. You need to change the event camera calibration from left to right:
![image](https://github.com/HKUSTGZ-IADC/iadc_dataset_tools/assets/56758695/504f07f6-c12f-42c6-a035-23d4f1d81df5)

**Comment by lucky9-cyou** [comment]
Could you please tell me the difference between the `ouster00` and `ouster00_undistort`? And why use the relative transform matrix between the `camera` and `body IMU` to project the `ouster00_undistort` point cloud onto the camera plane rather than `ouster00`.

And could you please provide fusionportable v2 dataset download link?
![image](https://github.com/HKUSTGZ-IADC/iadc_dataset_tools/assets/56758695/e16d4226-d574-4d85-82d5-2f8d680d5874)

**Comment by gogojjh** [comment]
LiDAR's points will have distortion due to the moving vehicle. Therefore, I undistort the point cloud using the fastlio2 algorithm, and the point cloud is transformed into the body_imu frame. For the ouster point clouds, they are defined in the ouster00 coordinate system. 
FusionPortable v2 will be released in two months.

**Comment by lucky9-cyou** [comment]
> LiDAR's points will have distortion due to the moving vehicle. Therefore, I undistort the point cloud using the fastlio2 algorithm, and the point cloud is transformed into the body_imu frame. For the ouster point clouds, they are defined in the ouster00 coordinate system. FusionPortable v2 will be released in two months.

Got it. Thanks for your reply very much.
